# -*- coding: utf-8 -*-
# Copyright (C) 2020 Lovac42
# Support: https://github.com/lovac42/DancingBaloney
# License: GNU GPL, version 3 or later; http://www.gnu.org/copyleft/gpl.html

# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from ..lib.com.lovac42.anki.version import ANKI21

if ANKI21:
    from PyQt5 import QtCore, QtWidgets
else:
    from PyQt4 import QtCore, QtGui as QtWidgets


class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.setEnabled(True)
        Settings.resize(400, 400)
        self.Wallpaper = QtWidgets.QWidget()
        self.Wallpaper.setEnabled(True)
        self.Wallpaper.setObjectName("Wallpaper")
        self.toolbar_groupbox = QtWidgets.QGroupBox(self.Wallpaper)
        self.toolbar_groupbox.setGeometry(QtCore.QRect(10, 10, 371, 91))
        self.toolbar_groupbox.setObjectName("toolbar_groupbox")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.toolbar_groupbox)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 351, 60))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.toolbox_grid_layout = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.toolbox_grid_layout.setContentsMargins(0, 0, 0, 0)
        self.toolbox_grid_layout.setObjectName("toolbox_grid_layout")
        self.toolbar_color_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.toolbar_color_label.setObjectName("toolbar_color_label")
        self.toolbox_grid_layout.addWidget(self.toolbar_color_label, 0, 0, 1, 1)
        self.toolbar_color_input = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.toolbar_color_input.setObjectName("toolbar_color_input")
        self.toolbox_grid_layout.addWidget(self.toolbar_color_input, 0, 1, 1, 1)
        self.toolbar_color_button = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.toolbar_color_button.setEnabled(True)
        self.toolbar_color_button.setObjectName("toolbar_color_button")
        self.toolbox_grid_layout.addWidget(self.toolbar_color_button, 0, 2, 1, 1)
        self.toolbar_image_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.toolbar_image_label.setObjectName("toolbar_image_label")
        self.toolbox_grid_layout.addWidget(self.toolbar_image_label, 1, 0, 1, 1)
        self.toolbar_image_input = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.toolbar_image_input.setObjectName("toolbar_image_input")
        self.toolbox_grid_layout.addWidget(self.toolbar_image_input, 1, 1, 1, 1)
        self.toolbar_image_button = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.toolbar_image_button.setObjectName("toolbar_image_button")
        self.toolbox_grid_layout.addWidget(self.toolbar_image_button, 1, 2, 1, 1)
        self.mw_groupbox = QtWidgets.QGroupBox(self.Wallpaper)
        self.mw_groupbox.setGeometry(QtCore.QRect(10, 110, 371, 141))
        self.mw_groupbox.setObjectName("mw_groupbox")
        self.gridLayoutWidget = QtWidgets.QWidget(self.mw_groupbox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 20, 351, 112))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.mw_grid_layout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.mw_grid_layout.setContentsMargins(0, 0, 0, 0)
        self.mw_grid_layout.setObjectName("mw_grid_layout")
        self.mw_color_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.mw_color_label.setObjectName("mw_color_label")
        self.mw_grid_layout.addWidget(self.mw_color_label, 0, 0, 1, 1)
        self.mw_opacity_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.mw_opacity_label.setObjectName("mw_opacity_label")
        self.mw_grid_layout.addWidget(self.mw_opacity_label, 2, 0, 1, 1)
        self.mw_image_input = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.mw_image_input.setObjectName("mw_image_input")
        self.mw_grid_layout.addWidget(self.mw_image_input, 1, 2, 1, 1)
        self.mw_image_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.mw_image_label.setObjectName("mw_image_label")
        self.mw_grid_layout.addWidget(self.mw_image_label, 1, 0, 1, 1)
        self.mw_color_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.mw_color_button.setObjectName("mw_color_button")
        self.mw_grid_layout.addWidget(self.mw_color_button, 0, 3, 1, 1)
        self.mw_color_input = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.mw_color_input.setObjectName("mw_color_input")
        self.mw_grid_layout.addWidget(self.mw_color_input, 0, 2, 1, 1)
        self.mw_image_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.mw_image_button.setObjectName("mw_image_button")
        self.mw_grid_layout.addWidget(self.mw_image_button, 1, 3, 1, 1)
        self.mw_gear_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.mw_gear_label.setObjectName("mw_gear_label")
        self.mw_grid_layout.addWidget(self.mw_gear_label, 3, 0, 1, 1)
        self.mw_gear_input = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.mw_gear_input.setObjectName("mw_gear_input")
        self.mw_grid_layout.addWidget(self.mw_gear_input, 3, 2, 1, 1)
        self.mw_gear_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.mw_gear_button.setObjectName("mw_gear_button")
        self.mw_grid_layout.addWidget(self.mw_gear_button, 3, 3, 1, 1)
        self.mw_opacity_slider = QtWidgets.QSlider(self.gridLayoutWidget)
        self.mw_opacity_slider.setEnabled(True)
        self.mw_opacity_slider.setMinimum(1)
        self.mw_opacity_slider.setMaximum(100)
        self.mw_opacity_slider.setSingleStep(10)
        self.mw_opacity_slider.setSliderPosition(100)
        self.mw_opacity_slider.setOrientation(QtCore.Qt.Horizontal)
        self.mw_opacity_slider.setObjectName("mw_opacity_slider")
        self.mw_grid_layout.addWidget(self.mw_opacity_slider, 2, 2, 1, 1)
        self.mw_opacity_value = QtWidgets.QLabel(self.gridLayoutWidget)
        self.mw_opacity_value.setObjectName("mw_opacity_value")
        self.mw_grid_layout.addWidget(self.mw_opacity_value, 2, 3, 1, 1)
        self.btm_groupbox = QtWidgets.QGroupBox(self.Wallpaper)
        self.btm_groupbox.setGeometry(QtCore.QRect(10, 260, 371, 111))
        self.btm_groupbox.setObjectName("btm_groupbox")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.btm_groupbox)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 351, 81))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.btm_grid_layout = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.btm_grid_layout.setContentsMargins(0, 0, 0, 0)
        self.btm_grid_layout.setObjectName("btm_grid_layout")
        self.btm_image_input = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.btm_image_input.setObjectName("btm_image_input")
        self.btm_grid_layout.addWidget(self.btm_image_input, 1, 1, 1, 1)
        self.btm_image_label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.btm_image_label.setObjectName("btm_image_label")
        self.btm_grid_layout.addWidget(self.btm_image_label, 1, 0, 1, 1)
        self.btm_opacity_label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.btm_opacity_label.setObjectName("btm_opacity_label")
        self.btm_grid_layout.addWidget(self.btm_opacity_label, 2, 0, 1, 1)
        self.btm_color_label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.btm_color_label.setObjectName("btm_color_label")
        self.btm_grid_layout.addWidget(self.btm_color_label, 0, 0, 1, 1)
        self.btm_color_input = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.btm_color_input.setObjectName("btm_color_input")
        self.btm_grid_layout.addWidget(self.btm_color_input, 0, 1, 1, 1)
        self.btm_color_button = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btm_color_button.setObjectName("btm_color_button")
        self.btm_grid_layout.addWidget(self.btm_color_button, 0, 2, 1, 1)
        self.btm_image_button = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btm_image_button.setObjectName("btm_image_button")
        self.btm_grid_layout.addWidget(self.btm_image_button, 1, 2, 1, 1)
        self.btm_opacity_slider = QtWidgets.QSlider(self.gridLayoutWidget_2)
        self.btm_opacity_slider.setMinimum(1)
        self.btm_opacity_slider.setMaximum(100)
        self.btm_opacity_slider.setSingleStep(10)
        self.btm_opacity_slider.setSliderPosition(100)
        self.btm_opacity_slider.setOrientation(QtCore.Qt.Horizontal)
        self.btm_opacity_slider.setObjectName("btm_opacity_slider")
        self.btm_grid_layout.addWidget(self.btm_opacity_slider, 2, 1, 1, 1)
        self.btm_opacity_value = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.btm_opacity_value.setObjectName("btm_opacity_value")
        self.btm_grid_layout.addWidget(self.btm_opacity_value, 2, 2, 1, 1)
        Settings.addTab(self.Wallpaper, "")
        self.Themes = QtWidgets.QWidget()
        self.Themes.setObjectName("Themes")
        self.themes_groupbox = QtWidgets.QGroupBox(self.Themes)
        self.themes_groupbox.setGeometry(QtCore.QRect(10, 10, 381, 111))
        self.themes_groupbox.setObjectName("themes_groupbox")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.themes_groupbox)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 30, 361, 71))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.themes_grid_layout = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.themes_grid_layout.setContentsMargins(0, 0, 0, 0)
        self.themes_grid_layout.setObjectName("themes_grid_layout")
        self.theme_combobox = QtWidgets.QComboBox(self.gridLayoutWidget_4)
        self.theme_combobox.setObjectName("theme_combobox")
        self.themes_grid_layout.addWidget(self.theme_combobox, 0, 1, 1, 1)
        self.theme_opacity_slider = QtWidgets.QSlider(self.gridLayoutWidget_4)
        self.theme_opacity_slider.setMinimum(1)
        self.theme_opacity_slider.setMaximum(100)
        self.theme_opacity_slider.setSingleStep(10)
        self.theme_opacity_slider.setSliderPosition(100)
        self.theme_opacity_slider.setOrientation(QtCore.Qt.Horizontal)
        self.theme_opacity_slider.setObjectName("theme_opacity_slider")
        self.themes_grid_layout.addWidget(self.theme_opacity_slider, 1, 1, 1, 1)
        self.theme_opacity_label = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.theme_opacity_label.setObjectName("theme_opacity_label")
        self.themes_grid_layout.addWidget(self.theme_opacity_label, 1, 0, 1, 1)
        self.theme_label = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.theme_label.setObjectName("theme_label")
        self.themes_grid_layout.addWidget(self.theme_label, 0, 0, 1, 1)
        self.theme_opacity_value = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.theme_opacity_value.setObjectName("theme_opacity_value")
        self.themes_grid_layout.addWidget(self.theme_opacity_value, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.Themes)
        self.label_2.setGeometry(QtCore.QRect(30, 140, 301, 91))
        self.label_2.setScaledContents(False)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        Settings.addTab(self.Themes, "")

        self.retranslateUi(Settings)
        Settings.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "Wallpaper Settings"))
        self.toolbar_groupbox.setTitle(_translate("Settings", "Top Toolbar"))
        self.toolbar_color_label.setText(_translate("Settings", "Color:   "))
        self.toolbar_color_button.setText(_translate("Settings", "Colors"))
        self.toolbar_image_label.setText(_translate("Settings", "Image:"))
        self.toolbar_image_button.setText(_translate("Settings", "Browse"))
        self.mw_groupbox.setTitle(_translate("Settings", "Main Window"))
        self.mw_color_label.setText(_translate("Settings", "Color:"))
        self.mw_opacity_label.setText(_translate("Settings", "Opacity:"))
        self.mw_image_label.setText(_translate("Settings", "Image:"))
        self.mw_color_button.setText(_translate("Settings", "Colors"))
        self.mw_image_button.setText(_translate("Settings", "Browse"))
        self.mw_gear_label.setText(_translate("Settings", "Gear:"))
        self.mw_gear_button.setText(_translate("Settings", "Browse"))
        self.mw_opacity_value.setText(_translate("Settings", "100%"))
        self.btm_groupbox.setTitle(_translate("Settings", "Bottom Toolbar"))
        self.btm_image_label.setText(_translate("Settings", "Image:"))
        self.btm_opacity_label.setText(_translate("Settings", "Opacity:"))
        self.btm_color_label.setText(_translate("Settings", "Color:"))
        self.btm_color_button.setText(_translate("Settings", "Colors"))
        self.btm_image_button.setText(_translate("Settings", "Browse"))
        self.btm_opacity_value.setText(_translate("Settings", "100%"))
        Settings.setTabText(Settings.indexOf(self.Wallpaper), _translate("Settings", "Wallpaper"))
        self.themes_groupbox.setTitle(_translate("Settings", "Themes"))
        self.theme_opacity_label.setText(_translate("Settings", "Opacity:"))
        self.theme_label.setText(_translate("Settings", "Theme:"))
        self.theme_opacity_value.setText(_translate("Settings", "100%"))
        self.label_2.setText(_translate("Settings", "<html><head/><body><p>1) Themes take priority over wallpapers. </p><p><br/>2) Anki auto deletes the theme folder on each update, backup custom themes. Do not save any personal themes here.</p></body></html>"))
        Settings.setTabText(Settings.indexOf(self.Themes), _translate("Settings", "Themes"))


