# -*- coding: utf-8 -*-
# Copyright (C) 2020 Lovac42
# Support: https://github.com/lovac42/DancingBaloney
# License: GNU GPL, version 3 or later; http://www.gnu.org/copyleft/gpl.html

# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from ..lib.com.lovac42.anki.version import ANKI21 

if ANKI21:
    from PyQt5 import QtCore, QtGui, QtWidgets
else:
    from PyQt4 import QtCore, QtGui, QtGui as QtWidgets



class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.setEnabled(True)
        Settings.resize(399, 457)
        self.Wallpaper = QtWidgets.QWidget()
        self.Wallpaper.setEnabled(True)
        self.Wallpaper.setObjectName("Wallpaper")
        self.toolbar_groupbox = QtWidgets.QGroupBox(self.Wallpaper)
        self.toolbar_groupbox.setGeometry(QtCore.QRect(10, 10, 221, 91))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.toolbar_groupbox.setFont(font)
        self.toolbar_groupbox.setStyleSheet("")
        self.toolbar_groupbox.setObjectName("toolbar_groupbox")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.toolbar_groupbox)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(8, 20, 201, 61))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.toolbox_grid_layout = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.toolbox_grid_layout.setContentsMargins(0, 0, 0, 0)
        self.toolbox_grid_layout.setObjectName("toolbox_grid_layout")
        self.toolbar_color_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.toolbar_color_label.setMaximumSize(QtCore.QSize(32, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.toolbar_color_label.setFont(font)
        self.toolbar_color_label.setObjectName("toolbar_color_label")
        self.toolbox_grid_layout.addWidget(self.toolbar_color_label, 0, 0, 1, 1)
        self.toolbar_color_input = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolbar_color_input.sizePolicy().hasHeightForWidth())
        self.toolbar_color_input.setSizePolicy(sizePolicy)
        self.toolbar_color_input.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.toolbar_color_input.setFont(font)
        self.toolbar_color_input.setObjectName("toolbar_color_input")
        self.toolbox_grid_layout.addWidget(self.toolbar_color_input, 0, 1, 1, 1)
        self.toolbar_image_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.toolbar_image_label.setMaximumSize(QtCore.QSize(32, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.toolbar_image_label.setFont(font)
        self.toolbar_image_label.setObjectName("toolbar_image_label")
        self.toolbox_grid_layout.addWidget(self.toolbar_image_label, 1, 0, 1, 1)
        self.toolbar_image_input = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolbar_image_input.sizePolicy().hasHeightForWidth())
        self.toolbar_image_input.setSizePolicy(sizePolicy)
        self.toolbar_image_input.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.toolbar_image_input.setFont(font)
        self.toolbar_image_input.setObjectName("toolbar_image_input")
        self.toolbox_grid_layout.addWidget(self.toolbar_image_input, 1, 1, 1, 1)
        self.toolbar_color_button = QtWidgets.QToolButton(self.gridLayoutWidget_3)
        self.toolbar_color_button.setEnabled(True)
        self.toolbar_color_button.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.toolbar_color_button.setFont(font)
        self.toolbar_color_button.setObjectName("toolbar_color_button")
        self.toolbox_grid_layout.addWidget(self.toolbar_color_button, 0, 2, 1, 1)
        self.toolbar_image_button = QtWidgets.QToolButton(self.gridLayoutWidget_3)
        self.toolbar_image_button.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.toolbar_image_button.setFont(font)
        self.toolbar_image_button.setObjectName("toolbar_image_button")
        self.toolbox_grid_layout.addWidget(self.toolbar_image_button, 1, 2, 1, 1)
        self.mw_groupbox = QtWidgets.QGroupBox(self.Wallpaper)
        self.mw_groupbox.setGeometry(QtCore.QRect(10, 110, 371, 191))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.mw_groupbox.setFont(font)
        self.mw_groupbox.setObjectName("mw_groupbox")
        self.gridLayoutWidget = QtWidgets.QWidget(self.mw_groupbox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 20, 351, 162))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.mw_grid_layout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.mw_grid_layout.setContentsMargins(0, 0, 0, 0)
        self.mw_grid_layout.setObjectName("mw_grid_layout")
        self.mw_color_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.mw_color_label.setFont(font)
        self.mw_color_label.setObjectName("mw_color_label")
        self.mw_grid_layout.addWidget(self.mw_color_label, 0, 0, 1, 1)
        self.mw_image_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.mw_image_label.setFont(font)
        self.mw_image_label.setObjectName("mw_image_label")
        self.mw_grid_layout.addWidget(self.mw_image_label, 1, 0, 1, 1)
        self.mw_color_input = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.mw_color_input.setFont(font)
        self.mw_color_input.setObjectName("mw_color_input")
        self.mw_grid_layout.addWidget(self.mw_color_input, 0, 2, 1, 1)
        self.mw_gear_input = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.mw_gear_input.setFont(font)
        self.mw_gear_input.setObjectName("mw_gear_input")
        self.mw_grid_layout.addWidget(self.mw_gear_input, 4, 2, 1, 1)
        self.mw_image_input = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.mw_image_input.setFont(font)
        self.mw_image_input.setObjectName("mw_image_input")
        self.mw_grid_layout.addWidget(self.mw_image_input, 1, 2, 1, 1)
        self.mw_gear_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.mw_gear_label.setMaximumSize(QtCore.QSize(34, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.mw_gear_label.setFont(font)
        self.mw_gear_label.setObjectName("mw_gear_label")
        self.mw_grid_layout.addWidget(self.mw_gear_label, 4, 0, 1, 1)
        self.mw_color_button = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.mw_color_button.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.mw_color_button.setFont(font)
        self.mw_color_button.setObjectName("mw_color_button")
        self.mw_grid_layout.addWidget(self.mw_color_button, 0, 3, 1, 1)
        self.mw_image_button = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.mw_image_button.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.mw_image_button.setFont(font)
        self.mw_image_button.setObjectName("mw_image_button")
        self.mw_grid_layout.addWidget(self.mw_image_button, 1, 3, 1, 1)
        self.mw_gear_button = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.mw_gear_button.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.mw_gear_button.setFont(font)
        self.mw_gear_button.setObjectName("mw_gear_button")
        self.mw_grid_layout.addWidget(self.mw_gear_button, 4, 3, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.mw_flipH_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.mw_flipH_checkbox.setEnabled(True)
        self.mw_flipH_checkbox.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.mw_flipH_checkbox.setFont(font)
        self.mw_flipH_checkbox.setObjectName("mw_flipH_checkbox")
        self.verticalLayout_2.addWidget(self.mw_flipH_checkbox)
        self.mw_flipV_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.mw_flipV_checkbox.setEnabled(True)
        self.mw_flipV_checkbox.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.mw_flipV_checkbox.setFont(font)
        self.mw_flipV_checkbox.setObjectName("mw_flipV_checkbox")
        self.verticalLayout_2.addWidget(self.mw_flipV_checkbox)
        self.mw_grid_layout.addLayout(self.verticalLayout_2, 3, 3, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.mw_opacity_value = QtWidgets.QLabel(self.gridLayoutWidget)
        self.mw_opacity_value.setMinimumSize(QtCore.QSize(35, 0))
        self.mw_opacity_value.setMaximumSize(QtCore.QSize(35, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.mw_opacity_value.setFont(font)
        self.mw_opacity_value.setObjectName("mw_opacity_value")
        self.gridLayout.addWidget(self.mw_opacity_value, 0, 2, 1, 1)
        self.mw_opacity_slider = QtWidgets.QSlider(self.gridLayoutWidget)
        self.mw_opacity_slider.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.mw_opacity_slider.setFont(font)
        self.mw_opacity_slider.setMinimum(1)
        self.mw_opacity_slider.setMaximum(100)
        self.mw_opacity_slider.setSingleStep(1)
        self.mw_opacity_slider.setSliderPosition(100)
        self.mw_opacity_slider.setOrientation(QtCore.Qt.Horizontal)
        self.mw_opacity_slider.setObjectName("mw_opacity_slider")
        self.gridLayout.addWidget(self.mw_opacity_slider, 0, 1, 1, 1)
        self.mw_opacity_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.mw_opacity_label.setFont(font)
        self.mw_opacity_label.setObjectName("mw_opacity_label")
        self.gridLayout.addWidget(self.mw_opacity_label, 0, 0, 1, 1)
        self.mw_rotate_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.mw_rotate_label.setFont(font)
        self.mw_rotate_label.setObjectName("mw_rotate_label")
        self.gridLayout.addWidget(self.mw_rotate_label, 1, 0, 1, 1)
        self.mw_rotate_slider = QtWidgets.QSlider(self.gridLayoutWidget)
        self.mw_rotate_slider.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.mw_rotate_slider.setFont(font)
        self.mw_rotate_slider.setMaximum(360)
        self.mw_rotate_slider.setSingleStep(1)
        self.mw_rotate_slider.setPageStep(90)
        self.mw_rotate_slider.setProperty("value", 0)
        self.mw_rotate_slider.setSliderPosition(0)
        self.mw_rotate_slider.setOrientation(QtCore.Qt.Horizontal)
        self.mw_rotate_slider.setObjectName("mw_rotate_slider")
        self.gridLayout.addWidget(self.mw_rotate_slider, 1, 1, 1, 1)
        self.mw_zoom_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.mw_zoom_label.setFont(font)
        self.mw_zoom_label.setObjectName("mw_zoom_label")
        self.gridLayout.addWidget(self.mw_zoom_label, 2, 0, 1, 1)
        self.mw_zoom_slider = QtWidgets.QSlider(self.gridLayoutWidget)
        self.mw_zoom_slider.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.mw_zoom_slider.setFont(font)
        self.mw_zoom_slider.setMinimum(25)
        self.mw_zoom_slider.setMaximum(250)
        self.mw_zoom_slider.setSingleStep(1)
        self.mw_zoom_slider.setPageStep(25)
        self.mw_zoom_slider.setSliderPosition(100)
        self.mw_zoom_slider.setOrientation(QtCore.Qt.Horizontal)
        self.mw_zoom_slider.setObjectName("mw_zoom_slider")
        self.gridLayout.addWidget(self.mw_zoom_slider, 2, 1, 1, 1)
        self.mw_rotate_value = QtWidgets.QLabel(self.gridLayoutWidget)
        self.mw_rotate_value.setMinimumSize(QtCore.QSize(35, 0))
        self.mw_rotate_value.setMaximumSize(QtCore.QSize(35, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.mw_rotate_value.setFont(font)
        self.mw_rotate_value.setObjectName("mw_rotate_value")
        self.gridLayout.addWidget(self.mw_rotate_value, 1, 2, 1, 1)
        self.mw_zoom_value = QtWidgets.QLabel(self.gridLayoutWidget)
        self.mw_zoom_value.setMinimumSize(QtCore.QSize(35, 0))
        self.mw_zoom_value.setMaximumSize(QtCore.QSize(35, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.mw_zoom_value.setFont(font)
        self.mw_zoom_value.setObjectName("mw_zoom_value")
        self.gridLayout.addWidget(self.mw_zoom_value, 2, 2, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.mw_grid_layout.addLayout(self.horizontalLayout, 3, 2, 1, 1)
        self.btm_groupbox = QtWidgets.QGroupBox(self.Wallpaper)
        self.btm_groupbox.setGeometry(QtCore.QRect(10, 310, 371, 111))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btm_groupbox.setFont(font)
        self.btm_groupbox.setObjectName("btm_groupbox")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.btm_groupbox)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 351, 81))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.btm_grid_layout = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.btm_grid_layout.setContentsMargins(0, 0, 0, 0)
        self.btm_grid_layout.setObjectName("btm_grid_layout")
        self.btm_image_input = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btm_image_input.setFont(font)
        self.btm_image_input.setObjectName("btm_image_input")
        self.btm_grid_layout.addWidget(self.btm_image_input, 1, 1, 1, 1)
        self.btm_image_label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btm_image_label.setFont(font)
        self.btm_image_label.setObjectName("btm_image_label")
        self.btm_grid_layout.addWidget(self.btm_image_label, 1, 0, 1, 1)
        self.btm_color_label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btm_color_label.setFont(font)
        self.btm_color_label.setObjectName("btm_color_label")
        self.btm_grid_layout.addWidget(self.btm_color_label, 0, 0, 1, 1)
        self.btm_color_input = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btm_color_input.setFont(font)
        self.btm_color_input.setObjectName("btm_color_input")
        self.btm_grid_layout.addWidget(self.btm_color_input, 0, 1, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btm_opacity_slider = QtWidgets.QSlider(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btm_opacity_slider.setFont(font)
        self.btm_opacity_slider.setMinimum(1)
        self.btm_opacity_slider.setMaximum(100)
        self.btm_opacity_slider.setSingleStep(1)
        self.btm_opacity_slider.setSliderPosition(100)
        self.btm_opacity_slider.setOrientation(QtCore.Qt.Horizontal)
        self.btm_opacity_slider.setObjectName("btm_opacity_slider")
        self.gridLayout_2.addWidget(self.btm_opacity_slider, 0, 1, 1, 1)
        self.btm_opacity_label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btm_opacity_label.setFont(font)
        self.btm_opacity_label.setObjectName("btm_opacity_label")
        self.gridLayout_2.addWidget(self.btm_opacity_label, 0, 0, 1, 1)
        self.btm_opacity_value = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.btm_opacity_value.setMinimumSize(QtCore.QSize(35, 0))
        self.btm_opacity_value.setMaximumSize(QtCore.QSize(35, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btm_opacity_value.setFont(font)
        self.btm_opacity_value.setObjectName("btm_opacity_value")
        self.gridLayout_2.addWidget(self.btm_opacity_value, 0, 2, 1, 1)
        self.btm_grid_layout.addLayout(self.gridLayout_2, 3, 1, 1, 1)
        self.btm_color_button = QtWidgets.QToolButton(self.gridLayoutWidget_2)
        self.btm_color_button.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btm_color_button.setFont(font)
        self.btm_color_button.setObjectName("btm_color_button")
        self.btm_grid_layout.addWidget(self.btm_color_button, 0, 2, 1, 1)
        self.btm_image_button = QtWidgets.QToolButton(self.gridLayoutWidget_2)
        self.btm_image_button.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btm_image_button.setFont(font)
        self.btm_image_button.setObjectName("btm_image_button")
        self.btm_grid_layout.addWidget(self.btm_image_button, 1, 2, 1, 1)
        self.btm_hide_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.btm_hide_checkbox.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.btm_hide_checkbox.setFont(font)
        self.btm_hide_checkbox.setObjectName("btm_hide_checkbox")
        self.btm_grid_layout.addWidget(self.btm_hide_checkbox, 3, 2, 1, 1)
        self.menubar_groupbox = QtWidgets.QGroupBox(self.Wallpaper)
        self.menubar_groupbox.setGeometry(QtCore.QRect(239, 10, 141, 91))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.menubar_groupbox.setFont(font)
        self.menubar_groupbox.setStyleSheet("")
        self.menubar_groupbox.setObjectName("menubar_groupbox")
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.menubar_groupbox)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(10, 20, 121, 61))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.menubar_text_input = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.menubar_text_input.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.menubar_text_input.setFont(font)
        self.menubar_text_input.setObjectName("menubar_text_input")
        self.gridLayout_4.addWidget(self.menubar_text_input, 0, 1, 1, 1)
        self.menubar_color_input = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.menubar_color_input.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.menubar_color_input.setFont(font)
        self.menubar_color_input.setObjectName("menubar_color_input")
        self.gridLayout_4.addWidget(self.menubar_color_input, 1, 1, 1, 1)
        self.menubar_text_label = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.menubar_text_label.setMaximumSize(QtCore.QSize(30, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.menubar_text_label.setFont(font)
        self.menubar_text_label.setObjectName("menubar_text_label")
        self.gridLayout_4.addWidget(self.menubar_text_label, 0, 0, 1, 1)
        self.menubar_color_label = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.menubar_color_label.setMaximumSize(QtCore.QSize(30, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.menubar_color_label.setFont(font)
        self.menubar_color_label.setObjectName("menubar_color_label")
        self.gridLayout_4.addWidget(self.menubar_color_label, 1, 0, 1, 1)
        self.menubar_text_button = QtWidgets.QToolButton(self.gridLayoutWidget_6)
        self.menubar_text_button.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.menubar_text_button.setFont(font)
        self.menubar_text_button.setObjectName("menubar_text_button")
        self.gridLayout_4.addWidget(self.menubar_text_button, 0, 2, 1, 1)
        self.menubar_color_button = QtWidgets.QToolButton(self.gridLayoutWidget_6)
        self.menubar_color_button.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.menubar_color_button.setFont(font)
        self.menubar_color_button.setObjectName("menubar_color_button")
        self.gridLayout_4.addWidget(self.menubar_color_button, 1, 2, 1, 1)
        Settings.addTab(self.Wallpaper, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.css_groupbox = QtWidgets.QGroupBox(self.tab)
        self.css_groupbox.setGeometry(QtCore.QRect(10, 100, 301, 311))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.css_groupbox.setFont(font)
        self.css_groupbox.setStyleSheet("")
        self.css_groupbox.setObjectName("css_groupbox")
        self.formLayoutWidget = QtWidgets.QWidget(self.css_groupbox)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 80, 281, 221))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.formLayoutWidget)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.css_db_input = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.css_db_input.setFont(font)
        self.css_db_input.setObjectName("css_db_input")
        self.gridLayout_6.addWidget(self.css_db_input, 0, 1, 1, 1)
        self.css_db_label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.css_db_label.setFont(font)
        self.css_db_label.setObjectName("css_db_label")
        self.gridLayout_6.addWidget(self.css_db_label, 0, 0, 1, 1)
        self.css_db_button = QtWidgets.QToolButton(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.css_db_button.setFont(font)
        self.css_db_button.setObjectName("css_db_button")
        self.gridLayout_6.addWidget(self.css_db_button, 0, 2, 1, 1)
        self.css_rev_input = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.css_rev_input.setFont(font)
        self.css_rev_input.setObjectName("css_rev_input")
        self.gridLayout_6.addWidget(self.css_rev_input, 2, 1, 1, 1)
        self.css_ov_input = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.css_ov_input.setFont(font)
        self.css_ov_input.setObjectName("css_ov_input")
        self.gridLayout_6.addWidget(self.css_ov_input, 1, 1, 1, 1)
        self.css_tb_label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.css_tb_label.setFont(font)
        self.css_tb_label.setObjectName("css_tb_label")
        self.gridLayout_6.addWidget(self.css_tb_label, 4, 0, 1, 1)
        self.css_ov_button = QtWidgets.QToolButton(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.css_ov_button.setFont(font)
        self.css_ov_button.setObjectName("css_ov_button")
        self.gridLayout_6.addWidget(self.css_ov_button, 1, 2, 1, 1)
        self.css_ov_label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.css_ov_label.setFont(font)
        self.css_ov_label.setObjectName("css_ov_label")
        self.gridLayout_6.addWidget(self.css_ov_label, 1, 0, 1, 1)
        self.css_rev_label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.css_rev_label.setFont(font)
        self.css_rev_label.setObjectName("css_rev_label")
        self.gridLayout_6.addWidget(self.css_rev_label, 2, 0, 1, 1)
        self.css_tbbtm_label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.css_tbbtm_label.setFont(font)
        self.css_tbbtm_label.setObjectName("css_tbbtm_label")
        self.gridLayout_6.addWidget(self.css_tbbtm_label, 5, 0, 1, 1)
        self.css_tb_input = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.css_tb_input.setFont(font)
        self.css_tb_input.setObjectName("css_tb_input")
        self.gridLayout_6.addWidget(self.css_tb_input, 4, 1, 1, 1)
        self.css_web_label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.css_web_label.setFont(font)
        self.css_web_label.setObjectName("css_web_label")
        self.gridLayout_6.addWidget(self.css_web_label, 3, 0, 1, 1)
        self.css_web_input = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.css_web_input.setFont(font)
        self.css_web_input.setObjectName("css_web_input")
        self.gridLayout_6.addWidget(self.css_web_input, 3, 1, 1, 1)
        self.css_tbbtm_input = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.css_tbbtm_input.setFont(font)
        self.css_tbbtm_input.setObjectName("css_tbbtm_input")
        self.gridLayout_6.addWidget(self.css_tbbtm_input, 5, 1, 1, 1)
        self.css_rev_button = QtWidgets.QToolButton(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.css_rev_button.setFont(font)
        self.css_rev_button.setObjectName("css_rev_button")
        self.gridLayout_6.addWidget(self.css_rev_button, 2, 2, 1, 1)
        self.css_web_button = QtWidgets.QToolButton(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.css_web_button.setFont(font)
        self.css_web_button.setObjectName("css_web_button")
        self.gridLayout_6.addWidget(self.css_web_button, 3, 2, 1, 1)
        self.css_tb_button = QtWidgets.QToolButton(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.css_tb_button.setFont(font)
        self.css_tb_button.setObjectName("css_tb_button")
        self.gridLayout_6.addWidget(self.css_tb_button, 4, 2, 1, 1)
        self.css_tbbtm_button = QtWidgets.QToolButton(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.css_tbbtm_button.setFont(font)
        self.css_tbbtm_button.setObjectName("css_tbbtm_button")
        self.gridLayout_6.addWidget(self.css_tbbtm_button, 5, 2, 1, 1)
        self.css_revbtm_input = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.css_revbtm_input.setFont(font)
        self.css_revbtm_input.setObjectName("css_revbtm_input")
        self.gridLayout_6.addWidget(self.css_revbtm_input, 6, 1, 1, 1)
        self.css_revbtm_label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.css_revbtm_label.setFont(font)
        self.css_revbtm_label.setObjectName("css_revbtm_label")
        self.gridLayout_6.addWidget(self.css_revbtm_label, 6, 0, 1, 1)
        self.css_revbtm_button = QtWidgets.QToolButton(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.css_revbtm_button.setFont(font)
        self.css_revbtm_button.setObjectName("css_revbtm_button")
        self.gridLayout_6.addWidget(self.css_revbtm_button, 6, 2, 1, 1)
        self.css_editor_label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.css_editor_label.setFont(font)
        self.css_editor_label.setObjectName("css_editor_label")
        self.gridLayout_6.addWidget(self.css_editor_label, 7, 0, 1, 1)
        self.css_editor_input = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.css_editor_input.setFont(font)
        self.css_editor_input.setObjectName("css_editor_input")
        self.gridLayout_6.addWidget(self.css_editor_input, 7, 1, 1, 1)
        self.css_editor_button = QtWidgets.QToolButton(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.css_editor_button.setFont(font)
        self.css_editor_button.setObjectName("css_editor_button")
        self.gridLayout_6.addWidget(self.css_editor_button, 7, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.css_groupbox)
        self.label_3.setGeometry(QtCore.QRect(20, 20, 241, 51))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.rev_groupbox = QtWidgets.QGroupBox(self.tab)
        self.rev_groupbox.setGeometry(QtCore.QRect(10, 10, 301, 81))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.rev_groupbox.setFont(font)
        self.rev_groupbox.setObjectName("rev_groupbox")
        self.gridLayoutWidget_7 = QtWidgets.QWidget(self.rev_groupbox)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(10, 20, 251, 51))
        self.gridLayoutWidget_7.setObjectName("gridLayoutWidget_7")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.rev_opacity_value = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.rev_opacity_value.setMaximumSize(QtCore.QSize(35, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rev_opacity_value.setFont(font)
        self.rev_opacity_value.setObjectName("rev_opacity_value")
        self.gridLayout_3.addWidget(self.rev_opacity_value, 1, 2, 1, 1)
        self.rev_opacity_slider = QtWidgets.QSlider(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rev_opacity_slider.setFont(font)
        self.rev_opacity_slider.setMinimum(1)
        self.rev_opacity_slider.setMaximum(100)
        self.rev_opacity_slider.setProperty("value", 80)
        self.rev_opacity_slider.setSliderPosition(80)
        self.rev_opacity_slider.setOrientation(QtCore.Qt.Horizontal)
        self.rev_opacity_slider.setObjectName("rev_opacity_slider")
        self.gridLayout_3.addWidget(self.rev_opacity_slider, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 1, 0, 1, 1)
        self.bg_reviewer_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.bg_reviewer_checkbox.setFont(font)
        self.bg_reviewer_checkbox.setObjectName("bg_reviewer_checkbox")
        self.gridLayout_3.addWidget(self.bg_reviewer_checkbox, 0, 0, 1, 3)
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(330, 40, 46, 371))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.trans_gridlayout = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.trans_gridlayout.setContentsMargins(0, 0, 0, 0)
        self.trans_gridlayout.setObjectName("trans_gridlayout")
        self.mw_translateY_slider = QtWidgets.QSlider(self.gridLayoutWidget_5)
        self.mw_translateY_slider.setMaximumSize(QtCore.QSize(16777215, 400))
        self.mw_translateY_slider.setMinimum(-100)
        self.mw_translateY_slider.setMaximum(100)
        self.mw_translateY_slider.setSingleStep(1)
        self.mw_translateY_slider.setPageStep(5)
        self.mw_translateY_slider.setProperty("value", 0)
        self.mw_translateY_slider.setOrientation(QtCore.Qt.Vertical)
        self.mw_translateY_slider.setObjectName("mw_translateY_slider")
        self.trans_gridlayout.addWidget(self.mw_translateY_slider, 0, 1, 1, 1)
        self.mw_translateX_slider = QtWidgets.QSlider(self.gridLayoutWidget_5)
        self.mw_translateX_slider.setMaximumSize(QtCore.QSize(16777215, 400))
        self.mw_translateX_slider.setMinimum(-100)
        self.mw_translateX_slider.setMaximum(100)
        self.mw_translateX_slider.setPageStep(5)
        self.mw_translateX_slider.setProperty("value", 0)
        self.mw_translateX_slider.setSliderPosition(0)
        self.mw_translateX_slider.setOrientation(QtCore.Qt.Vertical)
        self.mw_translateX_slider.setObjectName("mw_translateX_slider")
        self.trans_gridlayout.addWidget(self.mw_translateX_slider, 0, 0, 1, 1)
        self.mw_translateX_value = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.mw_translateX_value.setObjectName("mw_translateX_value")
        self.trans_gridlayout.addWidget(self.mw_translateX_value, 1, 0, 1, 1)
        self.mw_translateY_value = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.mw_translateY_value.setObjectName("mw_translateY_value")
        self.trans_gridlayout.addWidget(self.mw_translateY_value, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(330, 10, 51, 31))
        self.label_4.setObjectName("label_4")
        Settings.addTab(self.tab, "")
        self.Presets = QtWidgets.QWidget()
        self.Presets.setObjectName("Presets")
        self.groupBox_2 = QtWidgets.QGroupBox(self.Presets)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 40, 371, 101))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(40, 30, 121, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.Presets)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 160, 371, 121))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.save_preset_button = QtWidgets.QPushButton(self.Presets)
        self.save_preset_button.setEnabled(False)
        self.save_preset_button.setGeometry(QtCore.QRect(160, 10, 221, 23))
        self.save_preset_button.setObjectName("save_preset_button")
        Settings.addTab(self.Presets, "")
        self.Themes = QtWidgets.QWidget()
        self.Themes.setObjectName("Themes")
        self.themes_groupbox = QtWidgets.QGroupBox(self.Themes)
        self.themes_groupbox.setGeometry(QtCore.QRect(10, 10, 371, 171))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.themes_groupbox.setFont(font)
        self.themes_groupbox.setObjectName("themes_groupbox")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.themes_groupbox)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 30, 351, 121))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.themes_grid_layout = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.themes_grid_layout.setContentsMargins(0, 0, 0, 0)
        self.themes_grid_layout.setObjectName("themes_grid_layout")
        self.theme_combobox = QtWidgets.QComboBox(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.theme_combobox.setFont(font)
        self.theme_combobox.setObjectName("theme_combobox")
        self.themes_grid_layout.addWidget(self.theme_combobox, 0, 1, 1, 1)
        self.theme_opacity_slider = QtWidgets.QSlider(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.theme_opacity_slider.setFont(font)
        self.theme_opacity_slider.setMinimum(1)
        self.theme_opacity_slider.setMaximum(100)
        self.theme_opacity_slider.setSingleStep(1)
        self.theme_opacity_slider.setSliderPosition(90)
        self.theme_opacity_slider.setOrientation(QtCore.Qt.Horizontal)
        self.theme_opacity_slider.setObjectName("theme_opacity_slider")
        self.themes_grid_layout.addWidget(self.theme_opacity_slider, 1, 1, 1, 1)
        self.theme_opacity_label = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.theme_opacity_label.setFont(font)
        self.theme_opacity_label.setObjectName("theme_opacity_label")
        self.themes_grid_layout.addWidget(self.theme_opacity_label, 1, 0, 1, 1)
        self.theme_label = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.theme_label.setFont(font)
        self.theme_label.setObjectName("theme_label")
        self.themes_grid_layout.addWidget(self.theme_label, 0, 0, 1, 1)
        self.theme_opacity_value = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.theme_opacity_value.setMinimumSize(QtCore.QSize(40, 0))
        self.theme_opacity_value.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.theme_opacity_value.setFont(font)
        self.theme_opacity_value.setObjectName("theme_opacity_value")
        self.themes_grid_layout.addWidget(self.theme_opacity_value, 1, 2, 1, 1)
        self.theme_rev_opacity_value = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.theme_rev_opacity_value.setMinimumSize(QtCore.QSize(40, 0))
        self.theme_rev_opacity_value.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.theme_rev_opacity_value.setFont(font)
        self.theme_rev_opacity_value.setObjectName("theme_rev_opacity_value")
        self.themes_grid_layout.addWidget(self.theme_rev_opacity_value, 2, 2, 1, 1)
        self.theme_rev_opacity_label = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.theme_rev_opacity_label.setFont(font)
        self.theme_rev_opacity_label.setObjectName("theme_rev_opacity_label")
        self.themes_grid_layout.addWidget(self.theme_rev_opacity_label, 2, 0, 1, 1)
        self.theme_rev_opacity_slider = QtWidgets.QSlider(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.theme_rev_opacity_slider.setFont(font)
        self.theme_rev_opacity_slider.setMinimum(1)
        self.theme_rev_opacity_slider.setMaximum(100)
        self.theme_rev_opacity_slider.setSingleStep(1)
        self.theme_rev_opacity_slider.setProperty("value", 80)
        self.theme_rev_opacity_slider.setSliderPosition(80)
        self.theme_rev_opacity_slider.setOrientation(QtCore.Qt.Horizontal)
        self.theme_rev_opacity_slider.setObjectName("theme_rev_opacity_slider")
        self.themes_grid_layout.addWidget(self.theme_rev_opacity_slider, 2, 1, 1, 1)
        self.theme_color_label = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.theme_color_label.setFont(font)
        self.theme_color_label.setObjectName("theme_color_label")
        self.themes_grid_layout.addWidget(self.theme_color_label, 3, 0, 1, 1)
        self.theme_color_input = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.theme_color_input.setFont(font)
        self.theme_color_input.setObjectName("theme_color_input")
        self.themes_grid_layout.addWidget(self.theme_color_input, 3, 1, 1, 1)
        self.theme_color_button = QtWidgets.QToolButton(self.gridLayoutWidget_4)
        self.theme_color_button.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.theme_color_button.setFont(font)
        self.theme_color_button.setObjectName("theme_color_button")
        self.themes_grid_layout.addWidget(self.theme_color_button, 3, 2, 1, 1)
        self.theme_warning = QtWidgets.QLabel(self.Themes)
        self.theme_warning.setGeometry(QtCore.QRect(50, 210, 301, 91))
        self.theme_warning.setScaledContents(False)
        self.theme_warning.setWordWrap(True)
        self.theme_warning.setObjectName("theme_warning")
        Settings.addTab(self.Themes, "")

        self.retranslateUi(Settings)
        Settings.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "Wallpaper Settings"))
        self.toolbar_groupbox.setTitle(_translate("Settings", "Top Toolbar"))
        self.toolbar_color_label.setText(_translate("Settings", "Color: "))
        self.toolbar_image_label.setText(_translate("Settings", "Image:"))
        self.toolbar_color_button.setText(_translate("Settings", "C"))
        self.toolbar_image_button.setText(_translate("Settings", "B"))
        self.mw_groupbox.setTitle(_translate("Settings", "Main Window"))
        self.mw_color_label.setText(_translate("Settings", "Color:"))
        self.mw_image_label.setText(_translate("Settings", "Image:"))
        self.mw_gear_label.setText(_translate("Settings", "Gear:"))
        self.mw_color_button.setText(_translate("Settings", "Colors"))
        self.mw_image_button.setText(_translate("Settings", "Browse"))
        self.mw_gear_button.setText(_translate("Settings", "Browse"))
        self.mw_flipH_checkbox.setToolTip(_translate("Settings", "<html><head/><body><p>Flip Horizontally</p></body></html>"))
        self.mw_flipH_checkbox.setText(_translate("Settings", "Flip Hor"))
        self.mw_flipV_checkbox.setToolTip(_translate("Settings", "<html><head/><body><p>Flip Vertically</p></body></html>"))
        self.mw_flipV_checkbox.setText(_translate("Settings", "Flip Vert"))
        self.mw_opacity_value.setText(_translate("Settings", "100%"))
        self.mw_opacity_label.setText(_translate("Settings", "Opacity:"))
        self.mw_rotate_label.setText(_translate("Settings", "Rotate:"))
        self.mw_zoom_label.setText(_translate("Settings", "Zoom:"))
        self.mw_rotate_value.setText(_translate("Settings", "0°"))
        self.mw_zoom_value.setText(_translate("Settings", "100%"))
        self.btm_groupbox.setTitle(_translate("Settings", "Bottom Toolbar"))
        self.btm_image_label.setText(_translate("Settings", "Image:"))
        self.btm_color_label.setText(_translate("Settings", "Color:"))
        self.btm_opacity_label.setText(_translate("Settings", "Opacity:"))
        self.btm_opacity_value.setText(_translate("Settings", "100%"))
        self.btm_color_button.setText(_translate("Settings", "Colors"))
        self.btm_image_button.setText(_translate("Settings", "Browse"))
        self.btm_hide_checkbox.setText(_translate("Settings", "Hide"))
        self.menubar_groupbox.setTitle(_translate("Settings", "Menu Toolbar"))
        self.menubar_text_label.setText(_translate("Settings", "Text:   "))
        self.menubar_color_label.setText(_translate("Settings", "BGnd:"))
        self.menubar_text_button.setText(_translate("Settings", "C"))
        self.menubar_color_button.setText(_translate("Settings", "C"))
        Settings.setTabText(Settings.indexOf(self.Wallpaper), _translate("Settings", "Wallpaper"))
        self.css_groupbox.setTitle(_translate("Settings", "System Stylesheet Replacement"))
        self.css_db_label.setText(_translate("Settings", "DeckBrowser:"))
        self.css_db_button.setText(_translate("Settings", "..."))
        self.css_tb_label.setText(_translate("Settings", "Toolbar:"))
        self.css_ov_button.setText(_translate("Settings", "..."))
        self.css_ov_label.setText(_translate("Settings", "Overview:"))
        self.css_rev_label.setText(_translate("Settings", "Reviewer:"))
        self.css_tbbtm_label.setText(_translate("Settings", "BottomTb:"))
        self.css_web_label.setText(_translate("Settings", "Webview:"))
        self.css_rev_button.setText(_translate("Settings", "..."))
        self.css_web_button.setText(_translate("Settings", "..."))
        self.css_tb_button.setText(_translate("Settings", "..."))
        self.css_tbbtm_button.setText(_translate("Settings", "..."))
        self.css_revbtm_label.setText(_translate("Settings", "RevBtmTb:"))
        self.css_revbtm_button.setText(_translate("Settings", "..."))
        self.css_editor_label.setText(_translate("Settings", "Editor:"))
        self.css_editor_button.setText(_translate("Settings", "..."))
        self.label_3.setText(_translate("Settings", "This section will replace Anki\'s system stylesheets with your custom stylesheets. Any changes made to Anki in future version will require your custom CSS to also be updated."))
        self.rev_groupbox.setTitle(_translate("Settings", "Reviewer"))
        self.rev_opacity_value.setText(_translate("Settings", "100%"))
        self.label.setText(_translate("Settings", "Opacity:"))
        self.bg_reviewer_checkbox.setText(_translate("Settings", "Show wallpaper during review?"))
        self.mw_translateY_slider.setToolTip(_translate("Settings", "<html><head/><body><p>Translate Y</p></body></html>"))
        self.mw_translateX_slider.setToolTip(_translate("Settings", "<html><head/><body><p>Translate X</p></body></html>"))
        self.mw_translateX_value.setText(_translate("Settings", "100"))
        self.mw_translateY_value.setText(_translate("Settings", "100"))
        self.label_4.setToolTip(_translate("Settings", "<html><head/><body><p>You won\'t use this often, I ran out of space, so dumping this here. Let me know if you have a different idea where to place this.</p></body></html>"))
        self.label_4.setText(_translate("Settings", "Moves BG"))
        Settings.setTabText(Settings.indexOf(self.tab), _translate("Settings", "More..."))
        self.groupBox_2.setTitle(_translate("Settings", "Presets"))
        self.label_2.setText(_translate("Settings", "Not yet implemented..."))
        self.groupBox_3.setTitle(_translate("Settings", "Preset Groups"))
        self.save_preset_button.setText(_translate("Settings", "Save Settings As Preset"))
        Settings.setTabText(Settings.indexOf(self.Presets), _translate("Settings", "Presets"))
        self.themes_groupbox.setTitle(_translate("Settings", "Themes"))
        self.theme_opacity_label.setText(_translate("Settings", "Opacity:"))
        self.theme_label.setText(_translate("Settings", "Theme:"))
        self.theme_opacity_value.setText(_translate("Settings", "100%"))
        self.theme_rev_opacity_value.setText(_translate("Settings", "100%"))
        self.theme_rev_opacity_label.setText(_translate("Settings", "Reviewer Opacity"))
        self.theme_color_label.setText(_translate("Settings", "Color Hue"))
        self.theme_color_button.setText(_translate("Settings", "Color"))
        self.theme_warning.setText(_translate("Settings", "<html><head/><body><p>1) Themes take priority over wallpapers. </p><p><br/>2) Anki auto deletes the theme folder on each update, backup custom themes. Do not save any personal themes here.</p></body></html>"))
        Settings.setTabText(Settings.indexOf(self.Themes), _translate("Settings", "Themes"))


